verify that repo manifest is valid:
  image: registry.gitlab.com/soft.at.home/docker/oss-dbg:latest
  script:
    - export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
    - curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
    - gpg --recv-keys 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
    - curl -s https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ${REPO}
    - install -m 755 ${REPO} /usr/bin/repo

    - git checkout -b $CI_COMMIT_REF_NAME
    - git fetch --unshallow

    - python3 /usr/bin/repo init -u $(pwd) -b $CI_COMMIT_REF_NAME -m default.xml
    - python3 /usr/bin/repo sync
