variables:
  BUILD_TARGET: mod-amxb-dummy
  SAH_CI_IMAGE: "registry.gitlab.com/soft.at.home/docker/sah-nte:latest"
  PC_RUN_TEST: "on"  
  PC_PACKAGE_DEPS: libamxc=2.0.2 libamxb=4.10.0 libamxd=6.5.4
  SAH_NTE_IMAGE: $SAH_CI_IMAGE

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'
