variables:
  TEST_DEPS: amxrt psmisc libamxj libyajl-dev amxrt sah-services-pcb-bus-dev sah-lib-mtk-dev sah-services-pcb-app-dev sah-services-pcb-cli-dev
  BUILD_DEPS: libamxc libamxd libamxo libamxb libevent-dev
  BUILD_TARGET: la_threshold
  PC_BUILD_PACKAGE: "off"
  PC_DEPLOY_PACKAGE: "off"
  PC_PAGES: "off"
  PC_DOC_GEN: "off" 
  PC_CHECK_UNIT_TEST: "on"
  PC_CROSS_COMPILATION: "off"
  SAH_NTE_IMAGE: $SAH_CI_IMAGE

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'

